#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v2
# autospec commit: 250a6667ebd1
#
Name     : gpsbabel
Version  : 1.9.0
Release  : 2
URL      : https://github.com/GPSBabel/gpsbabel/archive/gpsbabel_1_9_0/gpsbabel-1.9.0.tar.gz
Source0  : https://github.com/GPSBabel/gpsbabel/archive/gpsbabel_1_9_0/gpsbabel-1.9.0.tar.gz
Summary  : Minizip zip file manipulation library
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause GPL-2.0 LGPL-2.0 LGPL-2.1 MIT ODbL-1.0 Zlib
Requires: gpsbabel-bin = %{version}-%{release}
Requires: gpsbabel-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : libusb-dev
BuildRequires : pkg-config
BuildRequires : qtwebengine-dev
BuildRequires : tzdata
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-No-solicitation.patch

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.2.13 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the gpsbabel package.
Group: Binaries
Requires: gpsbabel-license = %{version}-%{release}

%description bin
bin components for the gpsbabel package.


%package license
Summary: license components for the gpsbabel package.
Group: Default

%description license
license components for the gpsbabel package.


%prep
%setup -q -n gpsbabel-gpsbabel_1_9_0
cd %{_builddir}/gpsbabel-gpsbabel_1_9_0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697844619
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%cmake ..
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1697844619
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gpsbabel
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/gui/COPYING.txt %{buildroot}/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/mac/libusb/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/reference/gis.osm_places_free_1.license %{buildroot}/usr/share/package-licenses/gpsbabel/b898f35ae96d80dc09d818e0413d7dd1cc802cee || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/reference/gis.osm_railways_free_1.license %{buildroot}/usr/share/package-licenses/gpsbabel/481652f6d9accdfd0ce743687ba7074d77bed0df || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/shapelib/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/strptime/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/strptime/COPYING.LIB %{buildroot}/usr/share/package-licenses/gpsbabel/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/strptime/LICENSES %{buildroot}/usr/share/package-licenses/gpsbabel/7a61ff17323319d01ed2cae913a5febc968d29f3 || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/tools/qtci/LICENSE %{buildroot}/usr/share/package-licenses/gpsbabel/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/tools/uploadtool/LICENSE %{buildroot}/usr/share/package-licenses/gpsbabel/d4c9723f515c4739431b0cdb281a791019bbc790 || :
cp %{_builddir}/gpsbabel-gpsbabel_1_9_0/zlib/LICENSE %{buildroot}/usr/share/package-licenses/gpsbabel/233f44af3fb55dcc7fddfef8e77ac627b0008756 || :
pushd clr-build
%make_install ||:
popd
## install_append content
install -m 0755 -d %{buildroot}/usr/bin/
install -m 0755 -p clr-build/gpsbabel %{buildroot}/usr/bin/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpsbabel

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpsbabel/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/gpsbabel/233f44af3fb55dcc7fddfef8e77ac627b0008756
/usr/share/package-licenses/gpsbabel/481652f6d9accdfd0ce743687ba7074d77bed0df
/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/gpsbabel/7a61ff17323319d01ed2cae913a5febc968d29f3
/usr/share/package-licenses/gpsbabel/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/gpsbabel/b898f35ae96d80dc09d818e0413d7dd1cc802cee
/usr/share/package-licenses/gpsbabel/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/gpsbabel/d4c9723f515c4739431b0cdb281a791019bbc790
/usr/share/package-licenses/gpsbabel/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d
