#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: qmake
#
Name     : gpsbabel
Version  : 1.8.0
Release  : 1
URL      : https://github.com/GPSBabel/gpsbabel/archive/gpsbabel_1_8_0/gpsbabel-1.8.0.tar.gz
Source0  : https://github.com/GPSBabel/gpsbabel/archive/gpsbabel_1_8_0/gpsbabel-1.8.0.tar.gz
Summary  : Minizip zip file manipulation library
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 LGPL-2.0 LGPL-2.1 MIT ODbL-1.0
Requires: gpsbabel-bin = %{version}-%{release}
Requires: gpsbabel-license = %{version}-%{release}
BuildRequires : buildreq-kde
BuildRequires : buildreq-qmake
BuildRequires : libusb-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5WebChannel)
BuildRequires : pkgconfig(Qt5WebEngineWidgets)
BuildRequires : qtwebengine-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0002-No-solicitation.patch

%description
ZLIB DATA COMPRESSION LIBRARY
zlib 1.2.11 is a general purpose data compression library.  All the code is
thread safe.  The data format used by the zlib library is described by RFCs
(Request for Comments) 1950 to 1952 in the files
http://tools.ietf.org/html/rfc1950 (zlib format), rfc1951 (deflate format) and
rfc1952 (gzip format).

%package bin
Summary: bin components for the gpsbabel package.
Group: Binaries
Requires: gpsbabel-license = %{version}-%{release}

%description bin
bin components for the gpsbabel package.


%package license
Summary: license components for the gpsbabel package.
Group: Default

%description license
license components for the gpsbabel package.


%prep
%setup -q -n gpsbabel-gpsbabel_1_8_0
cd %{_builddir}/gpsbabel-gpsbabel_1_8_0
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%qmake -config ltcg -config fat-static-lto
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1691531511
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gpsbabel
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/gui/COPYING.txt %{buildroot}/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/mac/libusb/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/reference/gis.osm_places_free_1.license %{buildroot}/usr/share/package-licenses/gpsbabel/b898f35ae96d80dc09d818e0413d7dd1cc802cee || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/reference/gis.osm_railways_free_1.license %{buildroot}/usr/share/package-licenses/gpsbabel/481652f6d9accdfd0ce743687ba7074d77bed0df || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/shapelib/COPYING %{buildroot}/usr/share/package-licenses/gpsbabel/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/tools/qtci/LICENSE %{buildroot}/usr/share/package-licenses/gpsbabel/92170cdc034b2ff819323ff670d3b7266c8bffcd || :
cp %{_builddir}/gpsbabel-gpsbabel_1_8_0/tools/uploadtool/LICENSE %{buildroot}/usr/share/package-licenses/gpsbabel/d4c9723f515c4739431b0cdb281a791019bbc790 || :
%make_install
## install_append content
install -m 0755 -d %{buildroot}/usr/bin/
install -m 0755 -p gpsbabel %{buildroot}/usr/bin/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gpsbabel

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gpsbabel/481652f6d9accdfd0ce743687ba7074d77bed0df
/usr/share/package-licenses/gpsbabel/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/gpsbabel/92170cdc034b2ff819323ff670d3b7266c8bffcd
/usr/share/package-licenses/gpsbabel/b898f35ae96d80dc09d818e0413d7dd1cc802cee
/usr/share/package-licenses/gpsbabel/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/gpsbabel/d4c9723f515c4739431b0cdb281a791019bbc790
/usr/share/package-licenses/gpsbabel/df97bdf33b01f9ed42a799dd3ed7a1599dd0cb9d
